# Site settings
title: Patrick Shaughnessy
email: pshaughn86@gmail.com
description: A github pages site for developer Patrick Shaughnessy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://patrickshaughnessy.github.io" # the base hostname & protocol for your site
twitter_username: pattshaughnessy
github_username:  patrickshaughnessy

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-angular
